export const safeColors = [
  // { name: 'slate', label: 'Slate', class: 'bg-slate-500' },
  { name: 'gray', label: 'Gray', class: 'bg-gray-500' },
  { name: 'zinc', label: 'Zinc', class: 'bg-zinc-500' },
  { name: 'neutral', label: 'Neutral', class: 'bg-neutral-500' }, // no white
  { name: 'stone', label: 'Stone', class: 'bg-stone-500' },
  { name: 'red', label: 'Red', class: 'bg-red-500' }, // no white
  { name: 'orange', label: 'Orange', class: 'bg-orange-500' },
  { name: 'amber', label: 'Amber', class: 'bg-amber-500' },
  { name: 'yellow', label: 'Yellow', class: 'bg-yellow-500' },
  // { name: 'lime', label: 'Lime', class: 'bg-lime-500' },
  // { name: 'green', label: 'Green', class: 'bg-green-500' },
  { name: 'emerald', label: 'Emerald', class: 'bg-emerald-500' }, // no white
  { name: 'teal', label: 'Teal', class: 'bg-teal-500' },
  { name: 'cyan', label: 'Cyan', class: 'bg-cyan-500' }, // no white
  { name: 'sky', label: 'Sky', class: 'bg-sky-500' },
  { name: 'blue', label: 'Blue', class: 'bg-blue-500' }, // no white
  { name: 'violet', label: 'Violet', class: 'bg-violet-500' },
  { name: 'purple', label: 'Purple', class: 'bg-purple-500' },
  // { name: 'fuchsia', label: 'Fuchsia', class: 'bg-fuchsia-500' },
  { name: 'pink', label: 'Pink', class: 'bg-pink-500' }, // no white
  { name: 'rose', label: 'Rose', class: 'bg-rose-500' },
]

// Mapas para uso em classes dinâmicas (garante que o Tailwind scanneie estas strings)
export const bgColors: Record<string, string> = {
  slate: 'bg-slate-500',
  gray: 'bg-gray-500',
  zinc: 'bg-zinc-500',
  neutral: 'bg-neutral-500',
  stone: 'bg-stone-500',
  red: 'bg-red-500',
  orange: 'bg-orange-500',
  amber: 'bg-amber-500',
  yellow: 'bg-yellow-500',
  lime: 'bg-lime-500',
  green: 'bg-green-500',
  emerald: 'bg-emerald-500',
  teal: 'bg-teal-500',
  cyan: 'bg-cyan-500',
  sky: 'bg-sky-500',
  blue: 'bg-blue-500',
  indigo: 'bg-indigo-500',
  violet: 'bg-violet-500',
  purple: 'bg-purple-500',
  fuchsia: 'bg-fuchsia-500',
  pink: 'bg-pink-500',
  rose: 'bg-rose-500',
  // Legacy aliases
  info: 'bg-blue-500',
  success: 'bg-emerald-500',
  warning: 'bg-amber-500',
}

export const bgLightColors: Record<string, string> = {
  slate: 'bg-slate-200',
  gray: 'bg-gray-200',
  zinc: 'bg-zinc-200',
  neutral: 'bg-neutral-200',
  stone: 'bg-stone-200',
  red: 'bg-red-200',
  orange: 'bg-orange-200',
  amber: 'bg-amber-200',
  yellow: 'bg-yellow-200',
  lime: 'bg-lime-200',
  green: 'bg-green-200',
  emerald: 'bg-emerald-200',
  teal: 'bg-teal-200',
  cyan: 'bg-cyan-200',
  sky: 'bg-sky-200',
  blue: 'bg-blue-200',
  indigo: 'bg-indigo-200',
  violet: 'bg-violet-200',
  purple: 'bg-purple-200',
  fuchsia: 'bg-fuchsia-200',
  pink: 'bg-pink-200',
  rose: 'bg-rose-200',
  info: 'bg-blue-200',
  success: 'bg-emerald-200',
  warning: 'bg-amber-200',
}

export const resolveBgLightColor = (color: string) => {
  return bgLightColors[color] || 'bg-white'
}

export const borderColors: Record<string, string> = {
  slate: 'border-slate-500',
  gray: 'border-gray-500',
  zinc: 'border-zinc-500',
  neutral: 'border-neutral-500',
  stone: 'border-stone-500',
  red: 'border-red-500',
  orange: 'border-orange-500',
  amber: 'border-amber-500',
  yellow: 'border-yellow-500',
  lime: 'border-lime-500',
  green: 'border-green-500',
  emerald: 'border-emerald-500',
  teal: 'border-teal-500',
  cyan: 'border-cyan-500',
  sky: 'border-sky-500',
  blue: 'border-blue-500',
  indigo: 'border-indigo-500',
  violet: 'border-violet-500',
  purple: 'border-purple-500',
  fuchsia: 'border-fuchsia-500',
  pink: 'border-pink-500',
  rose: 'border-rose-500',
  // Legacy aliases
  info: 'border-blue-500',
  success: 'border-emerald-500',
  warning: 'border-amber-500',
}

export const borderLeftColors: Record<string, string> = {
  slate: 'border-l-slate-500',
  gray: 'border-l-gray-500',
  zinc: 'border-l-zinc-500',
  neutral: 'border-l-neutral-500',
  stone: 'border-l-stone-500',
  red: 'border-l-red-500',
  orange: 'border-l-orange-500',
  amber: 'border-l-amber-500',
  yellow: 'border-l-yellow-500',
  lime: 'border-l-lime-500',
  green: 'border-l-green-500',
  emerald: 'border-l-emerald-500',
  teal: 'border-l-teal-500',
  cyan: 'border-l-cyan-500',
  sky: 'border-l-sky-500',
  blue: 'border-l-blue-500',
  indigo: 'border-l-indigo-500',
  violet: 'border-l-violet-500',
  purple: 'border-l-purple-500',
  fuchsia: 'border-l-fuchsia-500',
  pink: 'border-l-pink-500',
  rose: 'border-l-rose-500',
  // Legacy aliases
  info: 'border-l-blue-500',
  success: 'border-l-emerald-500',
  warning: 'border-l-amber-500',
}

export const resolveColor = (color: string) => {
  const map: Record<string, string> = {
    info: 'blue',
    success: 'emerald',
    warning: 'amber',
    gray: 'slate',
  }
  const safeName = map[color] || color
  return `var(--color-${safeName}-500)`
}

// Ensure 800 shades are generated by Tailwind and have correct contrast
// Ensure 800 shades are generated by Tailwind and have correct contrast
export const bgDarkColors: Record<string, string> = {
  slate: 'bg-slate-800 !text-white',
  gray: 'bg-gray-800 !text-white',
  zinc: 'bg-zinc-800 !text-white',
  neutral: 'bg-neutral-800 !text-white',
  stone: 'bg-stone-800 !text-white',
  red: 'bg-red-800 !text-white',
  orange: 'bg-orange-800 !text-white',
  amber: 'bg-amber-800 !text-white',
  yellow: 'bg-yellow-800 !text-white',
  lime: 'bg-lime-800 !text-white',
  green: 'bg-green-800 !text-white',
  emerald: 'bg-emerald-800 !text-white',
  teal: 'bg-teal-800 !text-white',
  cyan: 'bg-cyan-800 !text-white',
  sky: 'bg-sky-800 !text-white',
  blue: 'bg-blue-800 !text-white',
  indigo: 'bg-indigo-800 !text-white',
  violet: 'bg-violet-800 !text-white',
  purple: 'bg-purple-800 !text-white',
  fuchsia: 'bg-fuchsia-800 !text-white',
  pink: 'bg-pink-800 !text-white',
  rose: 'bg-rose-800 !text-white',
  // Legacy
  info: 'bg-blue-800 !text-white',
  success: 'bg-emerald-800 !text-white',
  warning: 'bg-amber-800 !text-white',
}

// Special Primary Shades
export const primaryShades: Record<string, string> = {
  50: 'bg-primary-50 text-primary-900',
  100: 'bg-primary-100 text-primary-900',
  200: 'bg-primary-200 text-primary-900',
  300: 'bg-primary-300 text-primary-900',
  400: 'bg-primary-400 text-white',
  500: 'bg-primary-500 text-white',
  600: 'bg-primary-600 text-white',
  700: 'bg-primary-700 text-white',
  800: 'bg-primary-800 text-white',
  900: 'bg-primary-900 text-white',
  950: 'bg-primary-950 text-white',
}

export const textDarkColors: Record<string, string> = {
  slate: 'text-slate-800',
  gray: 'text-gray-800',
  zinc: 'text-zinc-800',
  neutral: 'text-neutral-800',
  stone: 'text-stone-800',
  red: 'text-red-800',
  orange: 'text-orange-800',
  amber: 'text-amber-800',
  yellow: 'text-yellow-800',
  lime: 'text-lime-800',
  green: 'text-green-800',
  emerald: 'text-emerald-800',
  teal: 'text-teal-800',
  cyan: 'text-cyan-800',
  sky: 'text-sky-800',
  blue: 'text-blue-800',
  indigo: 'text-indigo-800',
  violet: 'text-violet-800',
  purple: 'text-purple-800',
  fuchsia: 'text-fuchsia-800',
  pink: 'text-pink-800',
  rose: 'text-rose-800',
  // Legacy
  info: 'text-blue-800',
  success: 'text-emerald-800',
  warning: 'text-amber-800',
}
